apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: producer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MCCE2024/INENPT-G1-Argo.git
    targetRevision: main
    path: applications/producer/helm
    helm:
      values: |
        api:
          url: "http://api-service:3000"
          timeout: 30
        github:
          token: ""  # Leave empty here; set via secret in the cluster
        environment: "prod"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
